The following flake8 violations:
    ./tests/helpers.py:132:54: E226 missing whitespace around arithmetic operator
    ./tests/buyers/views/test_buyers.py:13:1: F811 redefinition of unused 'ContentLoader' from line 6
    ./tests/buyers/views/test_buyers.py:371:5: F811 redefinition of unused 'test_expired_framework_post_edit_brief_question' from line 361
    ./tests/buyers/views/test_buyers.py:381:5: F811 redefinition of unused 'test_expired_framework_post_edit_brief_question' from line 371
    ./tests/buyers/views/test_buyers.py:1283:9: F841 local variable 'document' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2320:53: F841 local variable 'get_framework_and_lot' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2352:53: F841 local variable 'get_framework_and_lot' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2354:62: F841 local variable 'current_user' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2373:53: F841 local variable 'get_framework_and_lot' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2375:62: F841 local variable 'current_user' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2422:13: F841 local variable 'length' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2423:13: F841 local variable 'offset' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2455:13: F841 local variable 'length' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2456:13: F841 local variable 'offset' is assigned to but never used
    ./tests/buyers/views/test_buyers.py:2559:42: F841 local variable 'get_context_data' is assigned to but never used

    ./tests/buyers/helpers/test_buyers_helpers.py:1:1: F401 'datetime' imported but unused
    ./tests/buyers/helpers/test_buyers_helpers.py:140:13: E123 closing bracket does not match indentation of opening bracket's line
    ./tests/buyers/helpers/test_ods.py:2:1: F401 'unittest' imported but unused
    ./tests/buyers/helpers/test_ods.py:8:1: F401 'hypothesis.assume' imported but unused
    ./tests/buyers/helpers/test_ods.py:105:32: F841 local variable 'Row' is assigned to but never used
    ./tests/buyers/helpers/test_ods.py:212:27: F821 undefined name 'fontface'
    ./tests/main/views/test_login.py:537:13: F841 local variable 'res' is assigned to but never used
    ./tests/main/views/test_login.py:543:13: F841 local variable 'res2' is assigned to but never used
    ./tests/main/views/test_marketplace.py:9:1: F401 'dmapiclient.APIError' imported but unused
    ./tests/main/views/test_marketplace.py:329:5: F811 redefinition of unused 'test_cookie_page' from line 324
    ./tests/main/views/test_marketplace.py:351:9: F841 local variable 'brief_title' is assigned to but never used
    ./tests/main/views/test_marketplace.py:352:9: F841 local variable 'brief_organisation' is assigned to but never used
    ./tests/main/views/test_marketplace.py:355:9: F841 local variable 'page_heading_h1' is assigned to but never used
    ./tests/main/views/test_marketplace.py:356:9: F841 local variable 'page_heading_context' is assigned to but never used
    ./tests/main/views/test_marketplace.py:748:9: E731 do not assign a lambda expression, use a def
    ./tests/main/views/test_marketplace.py:808:9: E731 do not assign a lambda expression, use a def
    ./tests/main/views/test_search.py:3:1: F401 'json' imported but unused
    ./tests/main/views/test_services.py:216:13: E123 closing bracket does not match indentation of opening bracket's line
    ./tests/main/views/test_services.py:243:13: E123 closing bracket does not match indentation of opening bracket's line
    ./tests/main/views/test_services.py:270:13: E123 closing bracket does not match indentation of opening bracket's line
    ./tests/main/views/test_services.py:288:13: E123 closing bracket does not match indentation of opening bracket's line
    ./tests/main/presenters/test_service_presenters.py:146:9: F841 local variable 'keys' is assigned to but never used
    ./app/buyers/__init__.py:33:1: E402 module level import not at top of file
    ./app/buyers/__init__.py:34:1: E402 module level import not at top of file
    ./app/buyers/__init__.py:35:1: E402 module level import not at top of file
    ./app/buyers/views/buyers.py:3:1: F401 'unicodecsv' imported but unused
    ./app/buyers/views/buyers.py:23:1: F401 'dmutils.formats.DATETIME_FORMAT' imported but unused
    ./app/buyers/views/buyers.py:148:36: E226 missing whitespace around arithmetic operator
    ./app/buyers/views/buyers.py:306:9: W503 line break before binary operator
    ./app/buyers/views/buyers.py:412:5: C901 'DownloadBriefResponsesView.generate_ods' is too complex (13)
    ./app/buyers/views/buyers.py:668:36: E226 missing whitespace around arithmetic operator
    ./app/buyers/helpers/buyers_helpers.py:2:1: F401 'datetime.datetime' imported but unused
    ./app/buyers/helpers/buyers_helpers.py:2:1: F401 'datetime.timedelta' imported but unused
    ./app/buyers/helpers/buyers_helpers.py:23:9: W503 line break before binary operator
    ./app/buyers/helpers/buyers_helpers.py:24:9: W503 line break before binary operator
    ./app/buyers/helpers/buyers_helpers.py:25:9: W503 line break before binary operator
    ./app/main/errors.py:18:1: F811 redefinition of unused 'page_not_found' from line 13
    ./app/main/views/login.py:206:37: E241 multiple spaces after ':'
    ./app/main/views/marketplace.py:4:1: F401 'datetime.datetime' imported but unused
    ./app/main/views/marketplace.py:8:1: F401 'flask_featureflags as feature' imported but unused
    ./app/main/views/marketplace.py:53:13: W503 line break before binary operator
    ./app/main/views/marketplace.py:100:36: E226 missing whitespace around arithmetic operator
    ./app/main/views/suppliers.py:13:5: F401 'urllib.parse.parse_qs' imported but unused
    ./app/main/views/suppliers.py:13:5: F401 'urllib.parse.urlparse' imported but unused
    ./app/main/presenters/search_summary.py:99:5: C901 'SearchSummary._group_request_filters' is too complex (22)
    ./app/main/presenters/service_presenters.py:19:21: E226 missing whitespace around arithmetic operator
    ./app/main/presenters/service_presenters.py:19:36: E226 missing whitespace around arithmetic operator
    ./app/main/presenters/service_presenters.py:108:40: F841 local variable 'e' is assigned to but never used
    ./app/main/presenters/service_presenters.py:131:28: E241 multiple spaces after ':'
    ./app/main/presenters/service_presenters.py:142:28: E241 multiple spaces after ':'
    ./app/main/presenters/service_presenters.py:166:29: E241 multiple spaces after ':'
    ./app/main/helpers/search_helpers.py:159:1: C901 'pagination' is too complex (9)
    ./app/main/helpers/search_helpers.py:201:9: E123 closing bracket does not match indentation of opening bracket's line