Remove custom styles from homepage
Updates the HTML of the supplier links on the homepage to use GOV.UK
Frontend styles instead of custom styles.

- Replace paragraphs with custom styles with unordered list of strong
  links
- Remove custom CSS classes
- Replace hardcoded urls with `url_for` where possible
- Replace aside with nav
- Add id to nav section to make testing easier
- Add ARIA label linking nav section to heading

The changes should have minimal visual impact, with one important
exception: the links are now underlined, to comply with WCAG Success
Criterion 1.4.1.