Remove usage of browse list component from homepage
Update HTML of buyer links on homepage to use GOV.UK Frontend styles
instead of custom browse list component.

- Replace use of Jinja template with plain HTML
- Replace hardcoded urls with `url_for`
- Use GOV.UK Frontend styles and overrides instead of custom styles
- Add id to nav section to make testing easier
- Add ARIA label linking nav section to heading

The changes should have minimal visual impact, with one important
exception: the links are now underlined, to comply with WCAG Success
Criterion 1.4.1.